version: '3'
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    command: jupyter lab --ip 0.0.0.0 --allow-root --no-browser


